ALTER TYPE "nft_state" RENAME VALUE 'DEPOSITED' TO 'IN_AKIVERSE';
ALTER TYPE "nft_state" RENAME VALUE 'DEPOSIT_PENDING' TO 'MOVING_TO_AKIVERSE';
ALTER TYPE "nft_state" RENAME VALUE 'WITHDRAWN' TO 'IN_WALLET';
ALTER TYPE "nft_state" RENAME VALUE 'WITHDRAWAL_PENDING' TO 'MOVING_TO_WALLET';
