# npm publish可能か判定する
name: check can publish

on:
  pull_request:
    # 対象ブランチ
    branches:
      - develop
    # 対象ファイル
    paths:
      - "src/models/external/**"

jobs:
  check-can-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # マージするプロジェクトチェックアウト
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: 20.7.0
          registry-url: "https://npm.pkg.github.com"
          scope: "@victgame"

      # publishに使用するpackage.jsonをrootに移動
      - name: cp package.json
        run: cp ./publish_settings/publish-package.json ./package.json

      - name: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          yarn install
          yarn add can-npm-publish

      # npm publish可能かチェック
      - name: check can publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx can-npm-publish --verbose
